const products = [
    {
      id: 0,
      name: "Gin and Tonic lite",
      price: 29.99,
      instock: 100,
      description:"650 ml",
      imgSrc: "bottle1.png",
      bg:"66BFBF",
      img_width:300 ,
      img_height:330 ,
    },
    {
      id: 1,
      name: "Rum and Cider",
      price: 24.99,
      instock: 43,
      description:"650ml",
      imgSrc: "bottle2.png",
      bg:"937DC2",
      img_width:300 ,
      img_height:330 ,
    },
    {
      id: 2,
      name: "Brandy and Ginger Ale",
      price: 19.99,
      instock: 10,
      description:"650 ml",
            imgSrc: "bottle3.png",
            bg:"CA4E79",
            img_width:300 ,
            img_height:330 ,
    },
    {
      id: 3,
      name: "Nutty Granola",
      price: 25.99,
      instock: 5,
      description:"435 gms",
            imgSrc: "granola1.png",
            bg:"146356",
            img_width:300 ,
            img_height:250 ,
    },
    {
      id: 4,
      name: "Fruit and Nut muesli",
      price: 29.99,
      instock: 4,
      description:"435 gms",
            imgSrc: "granola2.png",
            bg:"146356",
            img_width:300 ,
            img_height:250 ,
    },
    {
      id: 5,
      name: "Vanilla cake Mix",
      price: 39.99,
      instock: 40,
      description:"350 gms",
            imgSrc: "cakemix.png",
            bg:"865439",
            img_width:300 ,
            img_height:250 ,
    },
    {
        id: 6,
        name: "Pancake Mix",
        price: 39.99,
        instock: 40,
        description:"380 gms",
        imgSrc: "pancakemix.png",
        bg:"865439",
        img_width:300 ,
        img_height:250 ,
      },
      {
        id: 7,
        name: "Donut Mix",
        price: 39.99,
        instock: 40,
        description:"355 gms",
        imgSrc: "donutmix.png",
        bg:"865439",
        img_width:300 ,
        img_height:250 ,
       
      },
      {
        id: 8,
        name: "Oat Milk",
        price: 39.99,
        instock: 40,
        description:"870 ml",
        imgSrc: "oat_milk.png",
        bg:"876445",
        img_width:300 ,
        img_height:250 ,
      },
      {
        id: 9,
        name: "Almond Milk",
        price: 39.99,
        instock: 40,
        description:"870 ml",
        imgSrc: "almond_milk.png",
        bg:"876445",
        img_width:400 ,
        img_height:250 ,
      },
      {
        id: 10,
        name: "Soya Milk",
        price: 39.99,
        instock: 40,
        description:"870ml",
        imgSrc: "soy_milk.png",
        bg:"614124",
        img_width:300 ,
        img_height:250 ,
      },
      {
        id: 11,
        name: "Macaroon",
        price: 39.99,
        instock: 40,
        description:"Pack of 8",
        imgSrc: "macaroon.png",
        bg:"B25068",
        img_width:300 ,
        img_height:250 ,
      },
      {
        id: 12,
        name: "Pistachio Donut",
        price: 39.99,
        instock: 40,
        description:"Pack of 3",
        imgSrc: "pistadonut.png",
        bg:"B25068",
        img_width:300 ,
        img_height:250 ,
      },

      {
        id: 13,
        name: "Chocolate Donut",
        price: 39.99,
        instock: 40,
        description:"Pack of 3",
        imgSrc: "chocodonut.png",
        bg:"B25068",
        img_width:300 ,
        img_height:250 ,
      },
      {
        id: 14,
        name: "Cupcake-chocolate chip",
        price: 39.99,
        instock: 40,
        description:"Pack of 4",
        imgSrc: "cupcake.png",
        bg:"B25068",
        img_width:300 ,
        img_height:250 ,
      },
      {
        id: 15,
        name: "butter croissant",
        price: 39.99,
        instock: 40,
        description:"pack of 4",
        imgSrc: "croissant.png",
        bg:"B25068",
        img_width:300 ,
        img_height:250 ,
      },
      {
        id: 16,
        name: "Oat Bread ",
        price: 39.99,
        instock: 40,
        description:"1 loaf-550gms",
        imgSrc: "oatbread.png",
        bg:"B25068",
        img_width:300 ,
        img_height:250 ,
      },
      {
        id: 17,
        name: "Hazelnut Bread",
        price: 39.99,
        instock: 40,
        description:"1 loaf-550gms",
        imgSrc: "hazelnutbread.png",
        bg:"B25068",
        img_width:300 ,
        img_height:250 ,
      },
  ];